theme: minima
title: Decision Rubric
description: under construction.

markdown: kramdown

minima:
  # generate social links in footer
  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ericaaronmoore/" }


include:
  - _pages
  - files
encoding: "utf-8"
markdown_ext: "md"

collections:
  posts:
    output: true
    permalink: /:collection/:path/

defaults:
 - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      share: false
      comments: false


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

