theme: minima
title: Decision Rubric
description: under construction.


minima:
  # generate social links in footer
  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ericaaronmoore/" }

