theme: minima
title: Decision Rubric
description: under construction.

#turn on listing of posts on home page
show_excerpts: true

markdown: kramdown

minima:
  # generate social links in footer
  # social_links:
  # - { platform: linkedin,       user_url: "https://www.linkedin.com/in/ericaaronmoore/" }



# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

